name: 'Lint PR conventional commit'

on:
    pull_request_target:
        types: [opened, synchronize, reopened]

jobs:
    main:
        name: 'Validate PR title'
        runs-on: ubuntu-latest
        steps:
            # Default: https://github.com/commitizen/conventional-commit-types
            - uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
